# Generated by Django 3.1.4 on 2020-12-26 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualifications', models.TextField()),
                ('experience', models.IntegerField()),
                ('reporting_to', models.CharField(max_length=100)),
                ('add_candidate', models.ManyToManyField(related_name='candidates_for_this_job_interview', to=settings.AUTH_USER_MODEL, verbose_name='candidates_for_this_job_interview')),
                ('add_interviwer', models.ManyToManyField(related_name='inteviwers_for_this_job_interview', to=settings.AUTH_USER_MODEL, verbose_name='inteviwers_for_this_job_interview')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Problem solving', 'Problem solving'), ('Algorithms', 'Algorithms'), ('Coding', 'Coding')], max_length=250)),
                ('asking_ways', models.IntegerField(choices=[(1, 'Direct Questions'), (2, 'Problem questions'), (3, 'Coding Questions')], null=True)),
                ('question_set', models.TextField()),
                ('regarded_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('typeof_assessment', models.IntegerField(choices=[(1, 'Online assessment'), (2, 'Offline assessment')])),
                ('assessment_brief', models.TextField()),
                ('assessors', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='add assesors for this assessment')),
                ('regarded_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
