# Generated by Django 3.1.4 on 2020-12-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20201226_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='title',
            field=models.CharField(default='default title', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionset',
            name='title',
            field=models.CharField(default='default title', max_length=150),
            preserve_default=False,
        ),
    ]
